const mainUrl = "http://149.28.129.166:3002";

const SAVE_PROFILE_RESPONSE = "SAVE_PROFILE_RESPONSE";
const SAVE_LOGIN_RESPONSE = "SAVE_LOGIN_RESPONSE";

const SAVE_ADMIN_RESPONSE = "SAVE_ADMIN_RESPONSE";

const SAVE_EMPLOYEE_RESPONSE = "SAVE_EMPLOYEE_RESPONSE";
const String SERVER_FAILURE_MESSAGE = 'Something wrong! Try again';
const String CACHE_FAILURE_MESSAGE = 'Cache Failure';
